---
title: "Analyse temporelle"
format: pdf
editor: visual
---

```{r}
data <- read.csv("/Users/massambadiop/Documents/INSTITUT AGRO/M2 Sciences des données/Analyse de données massives sur R/Projet-R---shiny---2024--Agrocampus-1/qualite-des-cours-deau-vis-a-vis-des-nitrates-en-bretagne.csv",stringsAsFactors  = T,header =T)
str(data)
```

```{r}
install.packages("tidyverse")
install.packages("lubridate")
install.packages("zoo")
install.packages("forecast")

# Load libraries
library(tidyverse)
library(lubridate)
library(zoo)
library(forecast)
library(ggfortify)
library(plotly)
# Enlever les données manquantes
data <- data %>% 
  select(annee, concentration_moy) %>% 
  filter(!is.na(concentration_moy))

# Concentration en nitrate par année
Tend <- data %>% 
  group_by(annee) %>% 
  summarise(concentration_moy = mean(concentration_moy))

# Plot concentration en nitrate
ggplotly(ggplot(Tend, aes(x = annee, y = concentration_moy)) +
  geom_line(color = "blue") +
  geom_point(color = "red") +
  labs(title = "Evolution de la concentration en nitrates dans le temps",
       x = "Année",
       y = "Concentration moyenne en nitrates (mg/L)") +
  theme_gray())


# Transformation en serie temmporelle

data_ts <- ts(Tend$concentration_moy, start = min(Tend$annee), frequency = 1)

# Decompose en tendance et saisonnalité
data_decomposed <- decompose(data_ts)

# Plot the decomposed components
plot(nitrate_decomposed)


```

Analyse par département

```{r}

# J'ai enlevé les NA. A voir comment les traiter
nitrate_data <- data %>% 
  select(annee, libelle_departement, concentration_moy) %>% 
  filter(!is.na(concentration_moy))

# Calcul concentration moyenne par departement
nitrate_trend_dept <- nitrate_data %>% 
  group_by(annee, libelle_departement) %>% 
  summarise(mean_concentration = mean(concentration_moy))

# Graphique 
ggplotly(ggplot(nitrate_trend_dept, aes(x = annee, y = mean_concentration, color = libelle_departement)) +
  geom_line() + 
    geom_point(size=0.7) +
  labs(title = "Evolution de la Concentration moyenne en nitrates par Department",
       x = "Année",
       y = "Concentration moyenne en nitrates (mg/L)",
       color = "Departements") +
  theme_minimal() +
  theme(legend.position = "right")
  )


```
